### PR TITLE
Adds a prebuilt safariextz file, fixes a cut off icon

### PR DESCRIPTION
**Pull request by saagarjha**
This adds an icon for Safari Extension, as well as fixes the `octotree_opts` being cut off-both of these have been compiled into a `safariextz` file for easy installation.
This pull fixes the README to reflect this.
You may want to consider adding this to the Safari Extensions Gallery.

### CODE REVIEW

**Comment by caiofbpa** [comment]
This would definitely make the installation and update processes easier. IIRC publishing extensions to the Safari Gallery is free nowadays.

**Comment by saagarjha** [comment]
Just checked, it seems you need a valid developer account to both compile a Safari Extension as well as publish it on the Gallery.

**Comment by buunguyen** [comment]
Can you also include the source of the changes in this PR?

**Comment by saagarjha** [comment]
I actually just unzipped `Safari.zip`, loaded it into extension builder, added `Icon-64.png` and a fix in the CSS and built it with my certificate. I'm guessing I should modified the files `src` instead?

**Comment by buunguyen** [comment]
Yeah, please include only the src changes, I'll make a build myself. Thanks!

**Comment by saagarjha** [comment]
OK, I modified it…you may want to take a look though, as I went though a couple of merge conflicts by hand.

**Comment by buunguyen** [comment]
Thanks for working on this. I've decided to updated the gulp build script instead of duplicating the image. Also, not sure about all the changes to info.plist, if they're necessary please let me know and send another PR.

**Pull request closed without merging**
