### PR TITLE
Add jstree search feature

### PR DESCRIPTION
**Pull request by maliming**
### Add jstree search feature
fast location files, support case sensitive, fuzzy search, etc. jstree search option.

About [jstree search plugin:](https://www.jstree.com/api/#/?q=$.jstree.defaults.search&f=$.jstree.defaults.search)

### CODE REVIEW

**Comment by crashbell** [comment]
Thanks for your work. That basically looks good to me. I also have some comments below:
- The search works locally, that means, you can't search the files haven't been loaded. That seems not very useful in lazy-mode. That would be great if we can search the whole repo in lazy-mode (I do know it's tough, especially, for large repos).
- The link of search options is not intuitive. Should we write our own description as [Settings](https://github.com/buunguyen/octotree#settings)?
- The search options naming should be consistent with existing options.

**Comment by maliming** [comment]
@crashbell Very good advice, I also thought about the relevant issues before, do not know @buunguyen  is willing to join the search feature. If he is willing, I will continue to improve this feature.

**Comment by buunguyen** [comment]
This looks good. Only thing is people don't search all the times yet the search box appears in quite valued estate on the top. Maybe the search box is only displayed when people explicitly click a search icon or hit a short key combination? Also, I think the styling of the matched items can be improved, bold & italic don't look good IMO.

Agreed with the points @crashbell mentioned, esp. the point about simplifying the search options. The 1st could be tough but may not be of very high priority. If people click on nodes to expand in lazy mode and the matching still works with newly added items, I think that's probably fine.

**Comment by maliming** [comment]
I will continue to improve, hope that the next PR can let everyone accept, Thank you @crashbell @buunguyen the proposal that is very helpful to me.

**Comment by marsjaninzmarsa** [comment]
Maybe just leave this PR open, mark it as [WIP] and continue to working on it. Open PR → Better visibility → Chances for helpful colab and minimize risk of work duplication.

**Comment by marsjaninzmarsa** [comment]
Or just claim #397 as current WIP for this, that's confusing.

**Comment by buunguyen** [comment]
@maliming are you still interested in working on this?

**Comment by rajendraarora16** [comment]
Looking forward

**Comment by Jinkwon** [comment]
Looking forward so much 👍

**Pull request closed without merging**
