### PR TITLE
updated with new github link color

### PR DESCRIPTION
**Pull request by ergenekonyigit**
updated with new github link color.

### CODE REVIEW

**Comment by buunguyen** [comment]
Duplicated? https://github.com/buunguyen/octotree/pull/367

**Comment by ergenekonyigit** [comment]
@buunguyen seems like different. I changed folder and link color, not header.

**Comment by buunguyen** [comment]
Got it. Can you also change file icon color?

**Comment by ergenekonyigit** [comment]
Yes, updated new github folder icon color.

**Comment by buunguyen** [comment]
I mean the file icon as well. It's also changed in GitHub.

**Pull request merged**
