### PR TITLE
Add lazy-load option

### PR DESCRIPTION
**Pull request by crashbell**
I have changed `fetchData` syntax. Please review it :)

### CODE REVIEW

**Comment by buunguyen** [comment]
Looks good, almost there. Once address the comments, please re-issue the PR to v2 branch. Thanks.

**Comment by crashbell** [comment]
Thanks for reviewing it.

**Comment by buunguyen** [comment]
@crashbell I'm closing this now, please re-issue to v2 branch when you're done. Thanks.

**Comment by buunguyen** [comment]
@crashbell please note the adapter API has changed a bit by this commit https://github.com/buunguyen/octotree/commit/a81e7315a382221e54ccfe27a7212d7a366fdc2c that fixes #189.

**Pull request closed without merging**
