### PR TITLE
Update screenshot

### PR DESCRIPTION
**Pull request by crashbell**
### Description
Current screenshots on `README.md` is quite confusing when we don't use dark header for Octotree.

### Proposal
Update screenshots which have light headers.
Convert to `jpg` to reduce the file size.

@buunguyen I notice that the screenshots in Opera store is out of sync.

### CODE REVIEW

**Comment by buunguyen** [comment]
Thanks @crashbell, can you reduce file size (probably by reduce image size + quality a bit)?

**Comment by buunguyen** [comment]
Ping @crashbell

**Comment by crashbell** [comment]
@buunguyen I updated the `settings` image, for the rest, the size is not too different.

**Comment by buunguyen** [comment]
Thanks a lot!

**Pull request merged**
