### PR TITLE
fix for showing above github fork overlay

### PR DESCRIPTION
**Pull request by kellyselden**
Fix for this:
capture

### CODE REVIEW

**Comment by Mortiferr** [comment]
I've noticed this too. +1.

**Comment by buunguyen** [comment]
Thanks for this. I'm not sure how this affects GitLab since the z-index style is shared. Can you check and confirm?

**Comment by Mortiferr** [comment]
I don't use GitLab so @kellyselden can you take care of this?

**Comment by buunguyen** [comment]
Thanks for checking. Yes, github and gitlab have separate style file (see the `adapters` directory). So you can try moving the z-index from base to individual style file.

**Comment by kellyselden** [comment]
@buunguyen Will do soon.

**Comment by Mortiferr** [comment]
But does GitLab even have something like the GitHub fork overly? I didn't notice the background going dark like that when I tried to fork something on GitLab.

**Comment by Mortiferr** [comment]
Upon further investigation this isn't a problem at all on GitLab. This PR is good to go then as far as I can see. @buunguyen

**Comment by buunguyen** [comment]
@Mortiferr GitLab has a sidebar that Octotree needs to show on top.

**Pull request closed without merging**
