### PR TITLE
Fix GitLab URL for project/repository and file path

### PR DESCRIPTION
**Pull request by meip**
Two improvements for a robust GitLab adapter.

### CODE REVIEW

**Comment by crashbell** [comment]
@meip I tried to use `projectId` but if user hasn't logged in to GitLab, that ID will not be available because search box disappears.

**Comment by meip** [comment]
Thats true. Because of that I did this change with a fallback for non logged in users.

**Comment by buunguyen** [comment]
Can you clarify why we need to do this? I see your comment about Nginx/Apache, but from my testing the tree currently shows correctly. Is there a particular repo or specific usage when it doesn't work?

**Comment by meip** [comment]
Our internal GitLab is quite a bit outdated (GitLab 6.8.1) and with that specific version or the Apache configuration the request with NAMESPACE/PROJECT in URL received a 404.
I can't provide more detailed informations about the real issue because I'm not the admin of our GitLab. But I tested this fix also on gitlab.com repos and it works. Even as a fallback for non logged-in users which in that case uses the NAMESPACE/PROJECT request.

**Comment by buunguyen** [comment]
Merged by mistake and reverted.

Can you clarify what you have to introduce the `getPath`?

**Comment by meip** [comment]
This is a hook method for Adapter subclasses (b. e. concrete Gitlab adapter) to provide more specific path-resolution functionality.

**Comment by buunguyen** [comment]
I understand that part, just not sure why. Is it also related to your specific deployment? Because the current encoding works fine in my testing.

**Comment by meip** [comment]
Yes its related to our "special" deployment. Do we need more improvement on the PR for more robustness? Any ideas?

**Comment by buunguyen** [comment]
Can you add a bit code comment to clarify that and submit another PR?

**Comment by meip** [comment]
Sorry I can't provide more information on this specific behavior. But I think this issue is very related to #244

**Pull request merged**
