### PR TITLE
Migrate to WebExtension for FireFox

### PR DESCRIPTION
**Pull request by Ephemera**
### Description
Fix some legacy configuration and build scripts

### CODE REVIEW

**Comment by buunguyen** [comment]
@Ephemera thanks! Question: Opera also supports web extension and the script only reuses Chrome tasks. Can we do the same for Firefox? That would make maintenance easier.

**Comment by Ephemera** [comment]
@buunguyen 
It is almost same but [not exactly same](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities), so I think it need test more.

**Comment by buunguyen** [comment]
@Ephemera ok, thanks. I suppose this will make Firefox support enterprise GitHub, correct? It's fine if you can't tell, we can ask someone to test out, there are many people expecting Firefox to support GHE.

**Comment by buunguyen** [comment]
Hi @Ephemera, any update on this?

**Comment by Ephemera** [comment]
@buunguyen 
I'd misunderstood.
Firefox can not reuse Chrome tasks because It can't use `background.js`(WebExtensions [does not support `permissions`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities#Planned_APIs) yet.)
This also means can not support GHE yet.
If anyone knows more information, let me know.

**Comment by buunguyen** [comment]
I see. Can you resolve the conflicts?

**Comment by Ephemera** [comment]
@buunguyen 

I fixed it.

**Comment by buunguyen** [comment]
Thanks!

**Comment by marsjaninzmarsa** [comment]
@Ephemera:
> I'd misunderstood.

Yep.
> Firefox can not reuse Chrome tasks

It can.
> It can't use `background.js`

Totally [can](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/background).
> WebExtensions [does not support `permissions`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities#Planned_APIs) yet.

[Some of them](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions), yes. 
> This also means can not support GHE yet.

Why not? There are no any blockers. All we need [landed long time ago](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/optional_permissions).

Just [RTM](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities#Partially_supported_keys). To the end, when all is described in details. And yes, there was an misleading _Not Supported Yet_ notice, I've fixed it to _WIP_.

**Comment by Ephemera** [comment]
@marsjaninzmarsa 

`optional_permissions` was created on May 31. I do not know when it's included in the browser but the document was then created.
It seems possible now.

**Comment by Mte90** [comment]
Any chance for a new release soon?

**Comment by marsjaninzmarsa** [comment]
@Ephemera: to be specific: [support was added on March 26](https://bugzilla.mozilla.org/show_bug.cgi?id=1197420#c68) targeting [Firefox 55](https://developer.mozilla.org/en-US/Firefox/Releases/55#Changes_for_add-on_and_Mozilla_developers), scheduled for release on August 8. So... there are definitely some holes in documentation, unfortunately. :joy:
If I understand correctly, before 55 Firefox didn't support permissions at all, and all extensions had unlimited access? Or they were restricted distinctively? Im confused. :confused: 

@Mte90: I'll try to implement and test it before 55 release, until then you may try installing Chrome version via [Chrome  Store Foxified](https://addons.mozilla.org/firefox/addon/chrome-store-foxified/).

**Comment by Ephemera** [comment]
@marsjaninzmarsa 

Previously, it was possible to apply only to the **install time** with the key [`permissions`](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/permissions) in `manifest.json` so we would not be able to add GHE domain to permissions at runtime.

**Comment by buunguyen** [comment]
@marsjaninzmarsa any update on this?

**Comment by buunguyen** [comment]
@Ephemera does this work with Ff pre 56? How to test it with stable 54 locally? Thanks!

**Comment by Ephemera** [comment]
@buunguyen 

You can use `about:debugging` with stable FF54 also.

**Comment by buunguyen** [comment]
Yup, just found that out too. I tested and published to Mozilla store already. Thanks again for working on this. Any thought on support GitHub Enterprise URLs?

**Comment by timofonic** [comment]
@buunguyen What about 2.3.3 for Firefox too?

**Pull request merged**
