### PR TITLE
Add gitlab repo link

### PR DESCRIPTION
**Pull request by leocaseiro**
Add gitlab repo that might help some users as we discussed at #280 and #282

### CODE REVIEW

**Comment by buunguyen** [comment]
Why does it have to be the GitLab CE repo?

**Comment by leocaseiro** [comment]
Doesn't need to, but in my case, I don't have any GitLab repo and that was the less "branding" one I found so far. We can edit, something like:

> To add GitHub enterprise, go to a GitHub repo; otherwise, go to a GitLab repo (such as [gitlab-ce](https://gitlab.com/gitlab-org/gitlab-ce))

Is that nicer to you?

**Comment by buunguyen** [comment]
Sorry for taking long to respond. Yes, that change would be great. Can you modify and submit?

**Comment by leocaseiro** [comment]
Done!

**Comment by buunguyen** [comment]
Thanks a lot!

**Pull request merged**
